/*************************************************************************/
// Module        : LUT 256
// Description   : LUT for twiddle factors
// Author        : Generated by lut_gen.pl script
//
/*************************************************************************/
`ifndef sys_defs_header
`define sys_defs_header
    `include "sys_defs.vh"
`endif


module lut (
   input       clk,
   output      rst_n,
   input  [`INDEX_WIDTH - 1 : 0] index,
   input               valid,
   output  DATA_BUS twiddle
);
   logic [7:0] idx;
   assign idx = index;

   logic [15:0] twidI, twidQ;
   logic  [31:0] twiddle_w;
   assign  twiddle_w = (valid == 0) ? {1'b0,1'b1, 14'b0, 16'b0} : {twidI, twidQ};
	always_comb begin
		case (idx)

			8'd0: begin
				twidI = 16'd16384;
				twidQ = 16'd0;
			end

			8'd1: begin
				twidI = 16'd16382;
				twidQ = -16'd202;
			end

			8'd2: begin
				twidI = 16'd16379;
				twidQ = -16'd403;
			end

			8'd3: begin
				twidI = 16'd16372;
				twidQ = -16'd604;
			end

			8'd4: begin
				twidI = 16'd16364;
				twidQ = -16'd804;
			end

			8'd5: begin
				twidI = 16'd16353;
				twidQ = -16'd1005;
			end

			8'd6: begin
				twidI = 16'd16339;
				twidQ = -16'd1206;
			end

			8'd7: begin
				twidI = 16'd16323;
				twidQ = -16'd1406;
			end

			8'd8: begin
				twidI = 16'd16305;
				twidQ = -16'd1606;
			end

			8'd9: begin
				twidI = 16'd16284;
				twidQ = -16'd1806;
			end

			8'd10: begin
				twidI = 16'd16260;
				twidQ = -16'd2006;
			end

			8'd11: begin
				twidI = 16'd16234;
				twidQ = -16'd2205;
			end

			8'd12: begin
				twidI = 16'd16206;
				twidQ = -16'd2405;
			end

			8'd13: begin
				twidI = 16'd16175;
				twidQ = -16'd2603;
			end

			8'd14: begin
				twidI = 16'd16142;
				twidQ = -16'd2802;
			end

			8'd15: begin
				twidI = 16'd16107;
				twidQ = -16'd2999;
			end

			8'd16: begin
				twidI = 16'd16069;
				twidQ = -16'd3197;
			end

			8'd17: begin
				twidI = 16'd16028;
				twidQ = -16'd3394;
			end

			8'd18: begin
				twidI = 16'd15985;
				twidQ = -16'd3590;
			end

			8'd19: begin
				twidI = 16'd15940;
				twidQ = -16'd3786;
			end

			8'd20: begin
				twidI = 16'd15892;
				twidQ = -16'd3981;
			end

			8'd21: begin
				twidI = 16'd15842;
				twidQ = -16'd4176;
			end

			8'd22: begin
				twidI = 16'd15790;
				twidQ = -16'd4370;
			end

			8'd23: begin
				twidI = 16'd15735;
				twidQ = -16'd4564;
			end

			8'd24: begin
				twidI = 16'd15678;
				twidQ = -16'd4757;
			end

			8'd25: begin
				twidI = 16'd15618;
				twidQ = -16'd4949;
			end

			8'd26: begin
				twidI = 16'd15557;
				twidQ = -16'd5140;
			end

			8'd27: begin
				twidI = 16'd15492;
				twidQ = -16'd5330;
			end

			8'd28: begin
				twidI = 16'd15426;
				twidQ = -16'd5520;
			end

			8'd29: begin
				twidI = 16'd15357;
				twidQ = -16'd5709;
			end

			8'd30: begin
				twidI = 16'd15286;
				twidQ = -16'd5897;
			end

			8'd31: begin
				twidI = 16'd15212;
				twidQ = -16'd6084;
			end

			8'd32: begin
				twidI = 16'd15136;
				twidQ = -16'd6270;
			end

			8'd33: begin
				twidI = 16'd15058;
				twidQ = -16'd6456;
			end

			8'd34: begin
				twidI = 16'd14978;
				twidQ = -16'd6640;
			end

			8'd35: begin
				twidI = 16'd14895;
				twidQ = -16'd6823;
			end

			8'd36: begin
				twidI = 16'd14810;
				twidQ = -16'd7006;
			end

			8'd37: begin
				twidI = 16'd14723;
				twidQ = -16'd7187;
			end

			8'd38: begin
				twidI = 16'd14634;
				twidQ = -16'd7367;
			end

			8'd39: begin
				twidI = 16'd14543;
				twidQ = -16'd7546;
			end

			8'd40: begin
				twidI = 16'd14449;
				twidQ = -16'd7724;
			end

			8'd41: begin
				twidI = 16'd14353;
				twidQ = -16'd7901;
			end

			8'd42: begin
				twidI = 16'd14255;
				twidQ = -16'd8076;
			end

			8'd43: begin
				twidI = 16'd14155;
				twidQ = -16'd8250;
			end

			8'd44: begin
				twidI = 16'd14053;
				twidQ = -16'd8424;
			end

			8'd45: begin
				twidI = 16'd13948;
				twidQ = -16'd8595;
			end

			8'd46: begin
				twidI = 16'd13842;
				twidQ = -16'd8766;
			end

			8'd47: begin
				twidI = 16'd13733;
				twidQ = -16'd8935;
			end

			8'd48: begin
				twidI = 16'd13622;
				twidQ = -16'd9103;
			end

			8'd49: begin
				twidI = 16'd13510;
				twidQ = -16'd9269;
			end

			8'd50: begin
				twidI = 16'd13395;
				twidQ = -16'd9435;
			end

			8'd51: begin
				twidI = 16'd13278;
				twidQ = -16'd9598;
			end

			8'd52: begin
				twidI = 16'd13159;
				twidQ = -16'd9760;
			end

			8'd53: begin
				twidI = 16'd13038;
				twidQ = -16'd9921;
			end

			8'd54: begin
				twidI = 16'd12916;
				twidQ = -16'd10080;
			end

			8'd55: begin
				twidI = 16'd12791;
				twidQ = -16'd10238;
			end

			8'd56: begin
				twidI = 16'd12665;
				twidQ = -16'd10394;
			end

			8'd57: begin
				twidI = 16'd12536;
				twidQ = -16'd10549;
			end

			8'd58: begin
				twidI = 16'd12406;
				twidQ = -16'd10702;
			end

			8'd59: begin
				twidI = 16'd12273;
				twidQ = -16'd10854;
			end

			8'd60: begin
				twidI = 16'd12139;
				twidQ = -16'd11003;
			end

			8'd61: begin
				twidI = 16'd12003;
				twidQ = -16'd11151;
			end

			8'd62: begin
				twidI = 16'd11866;
				twidQ = -16'd11298;
			end

			8'd63: begin
				twidI = 16'd11726;
				twidQ = -16'd11443;
			end

			8'd64: begin
				twidI = 16'd11585;
				twidQ = -16'd11586;
			end

			8'd65: begin
				twidI = 16'd11442;
				twidQ = -16'd11727;
			end

			8'd66: begin
				twidI = 16'd11297;
				twidQ = -16'd11867;
			end

			8'd67: begin
				twidI = 16'd11150;
				twidQ = -16'd12004;
			end

			8'd68: begin
				twidI = 16'd11002;
				twidQ = -16'd12140;
			end

			8'd69: begin
				twidI = 16'd10853;
				twidQ = -16'd12274;
			end

			8'd70: begin
				twidI = 16'd10701;
				twidQ = -16'd12407;
			end

			8'd71: begin
				twidI = 16'd10548;
				twidQ = -16'd12537;
			end

			8'd72: begin
				twidI = 16'd10393;
				twidQ = -16'd12666;
			end

			8'd73: begin
				twidI = 16'd10237;
				twidQ = -16'd12792;
			end

			8'd74: begin
				twidI = 16'd10079;
				twidQ = -16'd12917;
			end

			8'd75: begin
				twidI = 16'd9920;
				twidQ = -16'd13039;
			end

			8'd76: begin
				twidI = 16'd9759;
				twidQ = -16'd13160;
			end

			8'd77: begin
				twidI = 16'd9597;
				twidQ = -16'd13279;
			end

			8'd78: begin
				twidI = 16'd9434;
				twidQ = -16'd13396;
			end

			8'd79: begin
				twidI = 16'd9268;
				twidQ = -16'd13511;
			end

			8'd80: begin
				twidI = 16'd9102;
				twidQ = -16'd13623;
			end

			8'd81: begin
				twidI = 16'd8934;
				twidQ = -16'd13734;
			end

			8'd82: begin
				twidI = 16'd8765;
				twidQ = -16'd13843;
			end

			8'd83: begin
				twidI = 16'd8594;
				twidQ = -16'd13949;
			end

			8'd84: begin
				twidI = 16'd8423;
				twidQ = -16'd14054;
			end

			8'd85: begin
				twidI = 16'd8249;
				twidQ = -16'd14156;
			end

			8'd86: begin
				twidI = 16'd8075;
				twidQ = -16'd14256;
			end

			8'd87: begin
				twidI = 16'd7900;
				twidQ = -16'd14354;
			end

			8'd88: begin
				twidI = 16'd7723;
				twidQ = -16'd14450;
			end

			8'd89: begin
				twidI = 16'd7545;
				twidQ = -16'd14544;
			end

			8'd90: begin
				twidI = 16'd7366;
				twidQ = -16'd14635;
			end

			8'd91: begin
				twidI = 16'd7186;
				twidQ = -16'd14724;
			end

			8'd92: begin
				twidI = 16'd7005;
				twidQ = -16'd14811;
			end

			8'd93: begin
				twidI = 16'd6822;
				twidQ = -16'd14896;
			end

			8'd94: begin
				twidI = 16'd6639;
				twidQ = -16'd14979;
			end

			8'd95: begin
				twidI = 16'd6455;
				twidQ = -16'd15059;
			end

			8'd96: begin
				twidI = 16'd6269;
				twidQ = -16'd15137;
			end

			8'd97: begin
				twidI = 16'd6083;
				twidQ = -16'd15213;
			end

			8'd98: begin
				twidI = 16'd5896;
				twidQ = -16'd15287;
			end

			8'd99: begin
				twidI = 16'd5708;
				twidQ = -16'd15358;
			end

			8'd100: begin
				twidI = 16'd5519;
				twidQ = -16'd15427;
			end

			8'd101: begin
				twidI = 16'd5329;
				twidQ = -16'd15493;
			end

			8'd102: begin
				twidI = 16'd5139;
				twidQ = -16'd15558;
			end

			8'd103: begin
				twidI = 16'd4948;
				twidQ = -16'd15619;
			end

			8'd104: begin
				twidI = 16'd4756;
				twidQ = -16'd15679;
			end

			8'd105: begin
				twidI = 16'd4563;
				twidQ = -16'd15736;
			end

			8'd106: begin
				twidI = 16'd4369;
				twidQ = -16'd15791;
			end

			8'd107: begin
				twidI = 16'd4175;
				twidQ = -16'd15843;
			end

			8'd108: begin
				twidI = 16'd3980;
				twidQ = -16'd15893;
			end

			8'd109: begin
				twidI = 16'd3785;
				twidQ = -16'd15941;
			end

			8'd110: begin
				twidI = 16'd3589;
				twidQ = -16'd15986;
			end

			8'd111: begin
				twidI = 16'd3393;
				twidQ = -16'd16029;
			end

			8'd112: begin
				twidI = 16'd3196;
				twidQ = -16'd16070;
			end

			8'd113: begin
				twidI = 16'd2998;
				twidQ = -16'd16108;
			end

			8'd114: begin
				twidI = 16'd2801;
				twidQ = -16'd16143;
			end

			8'd115: begin
				twidI = 16'd2602;
				twidQ = -16'd16176;
			end

			8'd116: begin
				twidI = 16'd2404;
				twidQ = -16'd16207;
			end

			8'd117: begin
				twidI = 16'd2204;
				twidQ = -16'd16235;
			end

			8'd118: begin
				twidI = 16'd2005;
				twidQ = -16'd16261;
			end

			8'd119: begin
				twidI = 16'd1805;
				twidQ = -16'd16285;
			end

			8'd120: begin
				twidI = 16'd1605;
				twidQ = -16'd16306;
			end

			8'd121: begin
				twidI = 16'd1405;
				twidQ = -16'd16324;
			end

			8'd122: begin
				twidI = 16'd1205;
				twidQ = -16'd16340;
			end

			8'd123: begin
				twidI = 16'd1004;
				twidQ = -16'd16354;
			end

			8'd124: begin
				twidI = 16'd803;
				twidQ = -16'd16365;
			end

			8'd125: begin
				twidI = 16'd603;
				twidQ = -16'd16373;
			end

			8'd126: begin
				twidI = 16'd402;
				twidQ = -16'd16380;
			end

			8'd127: begin
				twidI = 16'd201;
				twidQ = -16'd16383;
			end

			8'd128: begin
				twidI = 16'd0;
				twidQ = -16'd16384;
			end

			8'd129: begin
				twidI = -16'd202;
				twidQ = -16'd16383;
			end

			8'd130: begin
				twidI = -16'd403;
				twidQ = -16'd16380;
			end

			8'd131: begin
				twidI = -16'd604;
				twidQ = -16'd16373;
			end

			8'd132: begin
				twidI = -16'd804;
				twidQ = -16'd16365;
			end

			8'd133: begin
				twidI = -16'd1005;
				twidQ = -16'd16354;
			end

			8'd134: begin
				twidI = -16'd1206;
				twidQ = -16'd16340;
			end

			8'd135: begin
				twidI = -16'd1406;
				twidQ = -16'd16324;
			end

			8'd136: begin
				twidI = -16'd1606;
				twidQ = -16'd16306;
			end

			8'd137: begin
				twidI = -16'd1806;
				twidQ = -16'd16285;
			end

			8'd138: begin
				twidI = -16'd2006;
				twidQ = -16'd16261;
			end

			8'd139: begin
				twidI = -16'd2205;
				twidQ = -16'd16235;
			end

			8'd140: begin
				twidI = -16'd2405;
				twidQ = -16'd16207;
			end

			8'd141: begin
				twidI = -16'd2603;
				twidQ = -16'd16176;
			end

			8'd142: begin
				twidI = -16'd2802;
				twidQ = -16'd16143;
			end

			8'd143: begin
				twidI = -16'd2999;
				twidQ = -16'd16108;
			end

			8'd144: begin
				twidI = -16'd3197;
				twidQ = -16'd16070;
			end

			8'd145: begin
				twidI = -16'd3394;
				twidQ = -16'd16029;
			end

			8'd146: begin
				twidI = -16'd3590;
				twidQ = -16'd15986;
			end

			8'd147: begin
				twidI = -16'd3786;
				twidQ = -16'd15941;
			end

			8'd148: begin
				twidI = -16'd3981;
				twidQ = -16'd15893;
			end

			8'd149: begin
				twidI = -16'd4176;
				twidQ = -16'd15843;
			end

			8'd150: begin
				twidI = -16'd4370;
				twidQ = -16'd15791;
			end

			8'd151: begin
				twidI = -16'd4564;
				twidQ = -16'd15736;
			end

			8'd152: begin
				twidI = -16'd4757;
				twidQ = -16'd15679;
			end

			8'd153: begin
				twidI = -16'd4949;
				twidQ = -16'd15619;
			end

			8'd154: begin
				twidI = -16'd5140;
				twidQ = -16'd15558;
			end

			8'd155: begin
				twidI = -16'd5330;
				twidQ = -16'd15493;
			end

			8'd156: begin
				twidI = -16'd5520;
				twidQ = -16'd15427;
			end

			8'd157: begin
				twidI = -16'd5709;
				twidQ = -16'd15358;
			end

			8'd158: begin
				twidI = -16'd5897;
				twidQ = -16'd15287;
			end

			8'd159: begin
				twidI = -16'd6084;
				twidQ = -16'd15213;
			end

			8'd160: begin
				twidI = -16'd6270;
				twidQ = -16'd15137;
			end

			8'd161: begin
				twidI = -16'd6456;
				twidQ = -16'd15059;
			end

			8'd162: begin
				twidI = -16'd6640;
				twidQ = -16'd14979;
			end

			8'd163: begin
				twidI = -16'd6823;
				twidQ = -16'd14896;
			end

			8'd164: begin
				twidI = -16'd7006;
				twidQ = -16'd14811;
			end

			8'd165: begin
				twidI = -16'd7187;
				twidQ = -16'd14724;
			end

			8'd166: begin
				twidI = -16'd7367;
				twidQ = -16'd14635;
			end

			8'd167: begin
				twidI = -16'd7546;
				twidQ = -16'd14544;
			end

			8'd168: begin
				twidI = -16'd7724;
				twidQ = -16'd14450;
			end

			8'd169: begin
				twidI = -16'd7901;
				twidQ = -16'd14354;
			end

			8'd170: begin
				twidI = -16'd8076;
				twidQ = -16'd14256;
			end

			8'd171: begin
				twidI = -16'd8250;
				twidQ = -16'd14156;
			end

			8'd172: begin
				twidI = -16'd8424;
				twidQ = -16'd14054;
			end

			8'd173: begin
				twidI = -16'd8595;
				twidQ = -16'd13949;
			end

			8'd174: begin
				twidI = -16'd8766;
				twidQ = -16'd13843;
			end

			8'd175: begin
				twidI = -16'd8935;
				twidQ = -16'd13734;
			end

			8'd176: begin
				twidI = -16'd9103;
				twidQ = -16'd13623;
			end

			8'd177: begin
				twidI = -16'd9269;
				twidQ = -16'd13511;
			end

			8'd178: begin
				twidI = -16'd9435;
				twidQ = -16'd13396;
			end

			8'd179: begin
				twidI = -16'd9598;
				twidQ = -16'd13279;
			end

			8'd180: begin
				twidI = -16'd9760;
				twidQ = -16'd13160;
			end

			8'd181: begin
				twidI = -16'd9921;
				twidQ = -16'd13039;
			end

			8'd182: begin
				twidI = -16'd10080;
				twidQ = -16'd12917;
			end

			8'd183: begin
				twidI = -16'd10238;
				twidQ = -16'd12792;
			end

			8'd184: begin
				twidI = -16'd10394;
				twidQ = -16'd12666;
			end

			8'd185: begin
				twidI = -16'd10549;
				twidQ = -16'd12537;
			end

			8'd186: begin
				twidI = -16'd10702;
				twidQ = -16'd12407;
			end

			8'd187: begin
				twidI = -16'd10854;
				twidQ = -16'd12274;
			end

			8'd188: begin
				twidI = -16'd11003;
				twidQ = -16'd12140;
			end

			8'd189: begin
				twidI = -16'd11151;
				twidQ = -16'd12004;
			end

			8'd190: begin
				twidI = -16'd11298;
				twidQ = -16'd11867;
			end

			8'd191: begin
				twidI = -16'd11443;
				twidQ = -16'd11727;
			end

			8'd192: begin
				twidI = -16'd11586;
				twidQ = -16'd11586;
			end

			8'd193: begin
				twidI = -16'd11727;
				twidQ = -16'd11443;
			end

			8'd194: begin
				twidI = -16'd11867;
				twidQ = -16'd11298;
			end

			8'd195: begin
				twidI = -16'd12004;
				twidQ = -16'd11151;
			end

			8'd196: begin
				twidI = -16'd12140;
				twidQ = -16'd11003;
			end

			8'd197: begin
				twidI = -16'd12274;
				twidQ = -16'd10854;
			end

			8'd198: begin
				twidI = -16'd12407;
				twidQ = -16'd10702;
			end

			8'd199: begin
				twidI = -16'd12537;
				twidQ = -16'd10549;
			end

			8'd200: begin
				twidI = -16'd12666;
				twidQ = -16'd10394;
			end

			8'd201: begin
				twidI = -16'd12792;
				twidQ = -16'd10238;
			end

			8'd202: begin
				twidI = -16'd12917;
				twidQ = -16'd10080;
			end

			8'd203: begin
				twidI = -16'd13039;
				twidQ = -16'd9921;
			end

			8'd204: begin
				twidI = -16'd13160;
				twidQ = -16'd9760;
			end

			8'd205: begin
				twidI = -16'd13279;
				twidQ = -16'd9598;
			end

			8'd206: begin
				twidI = -16'd13396;
				twidQ = -16'd9435;
			end

			8'd207: begin
				twidI = -16'd13511;
				twidQ = -16'd9269;
			end

			8'd208: begin
				twidI = -16'd13623;
				twidQ = -16'd9103;
			end

			8'd209: begin
				twidI = -16'd13734;
				twidQ = -16'd8935;
			end

			8'd210: begin
				twidI = -16'd13843;
				twidQ = -16'd8766;
			end

			8'd211: begin
				twidI = -16'd13949;
				twidQ = -16'd8595;
			end

			8'd212: begin
				twidI = -16'd14054;
				twidQ = -16'd8424;
			end

			8'd213: begin
				twidI = -16'd14156;
				twidQ = -16'd8250;
			end

			8'd214: begin
				twidI = -16'd14256;
				twidQ = -16'd8076;
			end

			8'd215: begin
				twidI = -16'd14354;
				twidQ = -16'd7901;
			end

			8'd216: begin
				twidI = -16'd14450;
				twidQ = -16'd7724;
			end

			8'd217: begin
				twidI = -16'd14544;
				twidQ = -16'd7546;
			end

			8'd218: begin
				twidI = -16'd14635;
				twidQ = -16'd7367;
			end

			8'd219: begin
				twidI = -16'd14724;
				twidQ = -16'd7187;
			end

			8'd220: begin
				twidI = -16'd14811;
				twidQ = -16'd7006;
			end

			8'd221: begin
				twidI = -16'd14896;
				twidQ = -16'd6823;
			end

			8'd222: begin
				twidI = -16'd14979;
				twidQ = -16'd6640;
			end

			8'd223: begin
				twidI = -16'd15059;
				twidQ = -16'd6456;
			end

			8'd224: begin
				twidI = -16'd15137;
				twidQ = -16'd6270;
			end

			8'd225: begin
				twidI = -16'd15213;
				twidQ = -16'd6084;
			end

			8'd226: begin
				twidI = -16'd15287;
				twidQ = -16'd5897;
			end

			8'd227: begin
				twidI = -16'd15358;
				twidQ = -16'd5709;
			end

			8'd228: begin
				twidI = -16'd15427;
				twidQ = -16'd5520;
			end

			8'd229: begin
				twidI = -16'd15493;
				twidQ = -16'd5330;
			end

			8'd230: begin
				twidI = -16'd15558;
				twidQ = -16'd5140;
			end

			8'd231: begin
				twidI = -16'd15619;
				twidQ = -16'd4949;
			end

			8'd232: begin
				twidI = -16'd15679;
				twidQ = -16'd4757;
			end

			8'd233: begin
				twidI = -16'd15736;
				twidQ = -16'd4564;
			end

			8'd234: begin
				twidI = -16'd15791;
				twidQ = -16'd4370;
			end

			8'd235: begin
				twidI = -16'd15843;
				twidQ = -16'd4176;
			end

			8'd236: begin
				twidI = -16'd15893;
				twidQ = -16'd3981;
			end

			8'd237: begin
				twidI = -16'd15941;
				twidQ = -16'd3786;
			end

			8'd238: begin
				twidI = -16'd15986;
				twidQ = -16'd3590;
			end

			8'd239: begin
				twidI = -16'd16029;
				twidQ = -16'd3394;
			end

			8'd240: begin
				twidI = -16'd16070;
				twidQ = -16'd3197;
			end

			8'd241: begin
				twidI = -16'd16108;
				twidQ = -16'd2999;
			end

			8'd242: begin
				twidI = -16'd16143;
				twidQ = -16'd2802;
			end

			8'd243: begin
				twidI = -16'd16176;
				twidQ = -16'd2603;
			end

			8'd244: begin
				twidI = -16'd16207;
				twidQ = -16'd2405;
			end

			8'd245: begin
				twidI = -16'd16235;
				twidQ = -16'd2205;
			end

			8'd246: begin
				twidI = -16'd16261;
				twidQ = -16'd2006;
			end

			8'd247: begin
				twidI = -16'd16285;
				twidQ = -16'd1806;
			end

			8'd248: begin
				twidI = -16'd16306;
				twidQ = -16'd1606;
			end

			8'd249: begin
				twidI = -16'd16324;
				twidQ = -16'd1406;
			end

			8'd250: begin
				twidI = -16'd16340;
				twidQ = -16'd1206;
			end

			8'd251: begin
				twidI = -16'd16354;
				twidQ = -16'd1005;
			end

			8'd252: begin
				twidI = -16'd16365;
				twidQ = -16'd804;
			end

			8'd253: begin
				twidI = -16'd16373;
				twidQ = -16'd604;
			end

			8'd254: begin
				twidI = -16'd16380;
				twidQ = -16'd403;
			end

			8'd255: begin
				twidI = -16'd16383;
				twidQ = -16'd202;
			end

			default: begin
				twidI = 16'd0;
				twidQ = 16'd0;
			end

		endcase
	end

always_ff @(posedge clk) begin
   if (rst_n == 0) begin
      twiddle <= 0;
   end
   else begin
      twiddle.data <= #1 twiddle_w;
      twiddle.valid <= #1 valid;
   end
end
endmodule

